### ISSUE TITLE
code does not work when no categorical variable exists

### ISSUE THREAD

**Issue by Neelupar** [leonardodepaula/xgbimputer#1]
imputer = XGBImputer() without indicating indices for categorical, returns this error: 
X[:,self.categorical_features_index] = mode_simple_imputer.fit_transform(X[:,self.categorical_features_index])
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by GolAGitHub** [comment]
I encountered the same error. Any solution?

**Comment by leonardodepaula** [comment]
@Neelupar and @GolAGitHub, sorry for the delay. Are you still using the package? I couldn't reproduce the error. Can you give some more details to work on?

**Comment by leonardodepaula** [comment]
Closed, considering I could not reproduce the error.
